# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_id', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('owner', models.IntegerField()),
                ('community_shed_id', models.IntegerField()),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('lender', models.IntegerField()),
                ('borrower', models.IntegerField()),
                ('tool_id', models.IntegerField()),
                ('borrow_days', models.IntegerField()),
                ('borrow_message', models.CharField(max_length=200)),
                ('tool_lend_date', models.DateField()),
                ('tool_returned_date', models.DateField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address_line', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.BigIntegerField()),
                ('phone_no', models.BigIntegerField()),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('share_zone_id', models.BigIntegerField()),
                ('role_id', models.BigIntegerField()),
            ],
        ),
    ]
