# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityShed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_zone_id', models.IntegerField()),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip', models.IntegerField()),
                ('shed_coordinator', models.IntegerField()),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('transaction_id', models.IntegerField()),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShareZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField()),
                ('created_date', models.DateField()),
            ],
        ),
    ]
