# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0002_category_communityshed_feedback_notification_sharezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_line',
        ),
        migrations.AddField(
            model_name='user',
            name='address_line1',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='address_line2',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
