# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0004_auto_20161008_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolshareuser',
            name='created_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='toolshareuser',
            name='role_id',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='toolshareuser',
            name='share_zone_id',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='toolshareuser',
            name='updated_date',
            field=models.DateField(blank=True),
        ),
    ]
