# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-09 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0008_auto_20161009_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityshed',
            name='address_line2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityshed',
            name='share_zone_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityshed',
            name='shed_coordinator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
