# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0009_auto_20161009_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
