# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0010_auto_20161009_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityshed',
            name='share_zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.ShareZone'),
        ),
        migrations.AlterField(
            model_name='communityshed',
            name='shed_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.ToolShareUser'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tool_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.Tool'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.Transaction'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.ToolShareUser'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('BO', 'Borrowed'), ('DA', 'Deactivated'), ('RE', 'Reserved')], default='AVAILABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='toolshareuser',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.Role'),
        ),
        migrations.AlterField(
            model_name='toolshareuser',
            name='share_zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.ShareZone'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='toolsharesite.ToolShareUser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='toolsharesite.ToolShareUser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tool_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.Tool'),
        ),
    ]
