# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0012_auto_20161009_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='category_id',
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.Category'),
        ),
    ]
