# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0014_auto_20161010_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.ToolShareUser'),
        ),
    ]
