# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0015_auto_20161010_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('BO', 'Borrowed'), ('DA', 'Deactivated'), ('RE', 'Reserved')], default='AV', max_length=2),
        ),
        migrations.AlterField(
            model_name='toolshareuser',
            name='role',
            field=models.CharField(choices=[('US', 'User'), ('SC', 'Shed Coordinator'), ('AD', 'Admin')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('RE', 'Released')], default='PE', max_length=2),
        ),
    ]
