# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0016_auto_20161010_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='toolsharesite.ToolShareUser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='toolsharesite.ToolShareUser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.Tool'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tool_lend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tool_returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
