# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0017_auto_20161010_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tool_returned_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='community_shed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.CommunityShed'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tool_return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='borrow_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tool_lend_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
