# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0018_auto_20161010_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('RJ', 'Rejected'), ('RE', 'Released')], default='PE', max_length=2),
        ),
    ]
