# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0019_auto_20161010_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolshareuser',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
