# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-05 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0020_auto_20161011_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='condition',
            field=models.CharField(choices=[('G', 'Good'), ('A', 'Average'), ('B', 'Bad')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.FileField(default=datetime.datetime(2016, 11, 5, 22, 44, 19, 603742, tzinfo=utc), upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='location',
            field=models.CharField(choices=[('H', 'Home'), ('S', 'Community Shed')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='tool',
            name='specialInstruction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='toolshareuser',
            name='pickUpPref',
            field=models.CharField(default='Knock', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='tool_returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
