# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0023_auto_20161106_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolshareuser',
            name='pickUpPref',
        ),
        migrations.AddField(
            model_name='tool',
            name='pickUpPref',
            field=models.CharField(default='knock on door', max_length=100),
            preserve_default=False,
        ),
    ]
