# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-12 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0025_auto_20161110_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='community_shed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='community_shed',
        ),
        migrations.AddField(
            model_name='tool',
            name='share_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.ShareZone'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='share_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.ShareZone'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.Tool'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toolsharesite.Transaction'),
        ),
    ]
