# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0026_auto_20161112_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolshareuser',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
