# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0030_auto_20161114_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
