# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-03 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0031_auto_20161114_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
