# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import toolsharesite.models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0033_auto_20161204_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=toolsharesite.models.upload_location, width_field='width_field'),
        ),
    ]
