# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-05 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsharesite', '0034_auto_20161204_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='documents/', width_field='width_field'),
        ),
    ]
